#:schema node_modules/wrangler/config-schema.json
name = "workers-ai-image-playground"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[ai]
binding = "AI"

[vars]
CLOUDFLARE_ACCOUNT_ID = "8483c3ec7a0cbc54a8d660b5b9002b04"
